CREATE DATABASE DbGiger;

CREATE TABLE Mail(
idNewsletter INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(255) NOT NULL UNIQUE, 
date DATE DEFAULT NOW());


CREATE USER 'Giger'@'localhost' IDENTIFIED BY '2570';
GRANT ALL PRIVILEGES ON DbGiger.* TO 'Giger'@'localhost';
FLUSH PRIVILEGES;

